Optimalize epanet
tunczyk101/System-modelling-and-simulation pull request #7
Opened 2024-05-10 13:50 UTC by JudytaBakowska

2024-05-11 13:33 UTC, tunczyk101 requested changes
Nie wiem, czy to kwestia innego systemu, czy czegoś innego, ale u mnie to nie działa. Dzisiaj zrobię funkcję do wyciągania odpowiednich wartości z raportu. Będziesz mogła jej użyć tutaj.  To wsm to coś, do czego robiłaś mi ostatnio CR. 

Dużo komentarzy to kwestia formatowania.

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +    with open('epanet_model/model.inp', 'r') as f:
Tylko taka sugestia:
Może robić najpierw kopię modelu?
Żeby go nie popsuć?

2024-05-11 13:33 UTC, tunczyk101 commented on calculate_error.py
>  predicted_val = np.array([1, 2.0, 2.5, 4, 5, 8])
Może to całkiem usunąć albo użyć `if __name__ == "__main__":`
Linie od 34 do 38

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +def run_epanet_and_calculate_error(junctions,pipes, metric="mae"):
Brak spacji przed `pipes`

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +        report_section_end = lines.index('[END]\n')  # Zakładamy, że sekcja [REPORT] jest bezpośrednio przed sekcją [END]
Trochę zbyt długa linia

Przeniosłabym komentarz do następnej

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +
Za dużo o jedną pustą linię

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +    subprocess.run(['wine' , '/Users/judytabakowska/Desktop/epa/EPANET/build/bin/runepanet', 'epanet_model/model.inp', 'epanet_model/output.txt'],check=True)
Bez spacji po `'wine'`

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +    subprocess.run(['wine' , '/Users/judytabakowska/Desktop/epa/EPANET/build/bin/runepanet', 'epanet_model/model.inp', 'epanet_model/output.txt'],check=True)
Dodałabym zmienne do wywoływania, żeby było bardziej uniwersalnie, ale może też zostać jak jest. Będzie trzeba robić zmiany między systemami/komputerami, ale damy radę.

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +        report_section = '\n[REPORT]\nNODES ' + ', '.join(junctions) + '\nLINKS ' + ', '.join(pipes) + '\nFLOW YES\nPRESSURE YES\n'
Też trochę za długa

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +    main()
Po uruchomieniu otrzymuję

![image](https://github.com/tunczyk101/System-modelling-and-simulation/assets/92669642/9bacde80-c1b7-45f4-8f0f-0d6fa1160f1a)

W `output.txt`

W rezultacie nie działa cała optymalizacja.

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +        results = np.array([float(line.strip()) for line in f])
Obawiam się, że to nie zadziała
Output dla EPANET ma jeszcze nagłówki itp. W liniach z danymi, które nas interesują też są nazwy węzłów lub rur

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +        results = np.array([float(line.strip()) for line in f])
Wydaje mi się, że tu można skorzystać z tego czegoś co ja tworzyłam na ostatnie laby. Możemy albo zostawić tak jak jest - tylko na podstawie dwóch wartości optymalizujemy. Możemy też tak jak tu zrobić optymalizację na podstawie kilku/wszystkich.

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +junctions_to_adjust = [' SO/ZD', ' SW/SO', ' SW/RO', ' SD/GO1', ' SW/AN', ' HP7']
[Informacja] Takie stałe globalne to zazwyczaj się pisze samymi dużymi literami
(`JUNCTIONS = ...`)

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
Brak linii
Zgodnie z konwencją (PEP 8) powinny być 2 przed funkcją
// tak wiem, że straszne czepialstwo, ale potem na rozmowach o pracę się o to też czepiają

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +                lines[j + junctions_index] = '    '.join(parts) + '\n'  # Dodaj junctions_index, aby uwzględnić przesunięcie
Trochę zbyt długa linia

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +            if line.startswith('['):  # Zakończ przeszukiwanie po napotkaniu '['
Zawsze zaczynasz przeszukiwanie od linii `'[JUNCTIONS]\n'`, więc od razu wchodzisz do `if` i przerywasz pętlę

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +            if line.startswith('['):  # Zakończ przeszukiwanie po napotkaniu '['
Analogicznie

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
Za dużo o jedną linijkę

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
Dwie puste linie

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +def reset_params_to_zero():
Chyba nie musimy robić resetu, prawda (?)

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
2 puste linie przed funkcją

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +    error = run_epanet_and_calculate_error(junctions_to_adjust,pipes_to_adjust)
Brak spacji przed `reset_params_to_zero`

2024-05-11 13:33 UTC, tunczyk101 commented on epanet_end_error.py
> +    time.sleep(5)
Dlaczego sleep?
`subprocess.run` nie czeka na wykonanie polecenia?

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
2 line

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +    bounds = [(0,0.26)] * len(junctions_to_adjust) + [(0,5)] * len(pipes_to_adjust)
Brak spacji w tuplach
`[(0, 0.26)]` `[(0, 5)]`

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
Tab do usunięcia

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +
2 linie

2024-05-11 13:33 UTC, tunczyk101 commented on optimize_epanet.py
> +import numpy as np
Zbędny import

2024-05-11 18:19 UTC, tunczyk101 commented on epanet_end_error.py
> +        report_section = '\n[REPORT]\nNODES ' + ', '.join(junctions) + '\nLINKS ' + ', '.join(pipes) + '\nFLOW YES\nPRESSURE YES\n'
To można fstringiem zrobić
f"\n[REPORT]\nNODES {', '.join(junctions)} ..."

2024-05-11 20:42 UTC, tunczyk101 commented on epanet_end_error.py
> +    with open('epanet_model/model.inp', 'r') as f:
wielokrotnie dodajesz reports do pliku

2024-05-11 22:30 UTC, tunczyk101 commented
TODO

- funkcja wpisująca wartości do modelu/sieci: 
przekazywane wartości: x: list[float], np. [1, 3, 0.2 ....] co tam sobie `differential_evolution` wymyśli, długość x to liczba nodes oraz pipes w całym modelu (chyba 338 =  193 + 145) - coś analogicznego jak w tym do outputu

- funkcja dla `differential_evolution`
 użyj powyższej, aby zaktualizować model
 uruchom epanet
 użyj funkcji do outputu, aby uzyskać  rezultaty symulacji
 porównaj rezultaty z docelowymi wartościami (calculate_error) i zwróć ten wynik

- funkcja optymalizacji modelu
  bounds takiej długości jak x, jako funkcja do optymalizacji to co powyżej

2024-05-12 18:58 UTC, tunczyk101 requested changes
Chyba oprócz poniższych ok. Najważniejsze — szukamy dobrych wartości dla wszystkich elementów, nie tylko wybranych junctions lub pipes

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +            "[REPORT]\nNODES"
Może lepszy byłby f string 🤔 , ale może to moje osobiste upodobanie 🤷

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +        [r"D:\EPANET 2.2\runepanet.exe", optimalize_model, optimalize_output],
Wstaw to proszę do jakiejś zmiennej, żeby nie było trzeba podmieniać w dwóch miejscach

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +    if error > 0.001:
Czy nierówność nie powinna być w drugą stronę?

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +        sys.exit()
Jeżeli zrobisz tak, to nie mamy tego ostatniego wyniku. Brak zapisu do pliku itp.
Może użyć parametru `maxiter` dla differential_evolution?

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +        )
Ucinasz w ten sposób wszystko co jest poniżej report
Tam jeszcze jest kilka sekcji

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +    bounds = [(0, 0.26)] * len(junctions_to_adjust) + [(0, 5)] * len(pipes_to_adjust)
szukamy wartości dla wszystkich junctions i pipes.
Te wybrane są tylko do obliczania mae

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +def update_epanet_file(filename, x):
Powinno być dla wszystkich junctions i pipes w modelu
Nie tylko dla tych "wybranych"

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +junctions_to_adjust = [" SO/ZD ", " SW/SO ", " SW/RO ", " SD/GO1 ", " SW/AN ", " HP7 "]
Może DUŻYMI literami?

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +    for i in range(len(junctions_to_adjust)):
Wsm to nie wiem czy możemy demand optymalizować?

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +    for i in range(len(junctions_to_adjust)):
Bo ja tam pamiętam, że jakąś głupotę wpisałam. Możemy np. teraz zostawić tylko x dla pipes (Roughness)

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +def run_epanet_and_calculate_error(junctions, pipes, metric="mse"):
junctions i pipes nie jest używane

2024-05-12 18:58 UTC, tunczyk101 commented on optimize_epanet.py
> +    results_optimalize = get_simulation_results(optimalize_output)
Tam jest do poprawy return w `get_simulation_results`

Zmień proszę `return results` na `return [float(r) for r in results]`

2024-05-13 08:16 UTC, JudytaBakowska commented on optimize_epanet.py
> +        sys.exit()
właśnie jeśli o to chodzi, to wydaje mi się, że mamy normalnie ten ostatni plik. bo próbowałam z maxiter, ale mimo ustawienia dla testów na maxiter = 10, to i tak się nie zatrzymało tylko musiałam ręcznie to zatrzymywać

2024-06-30 20:02 UTC, merged